"""
LUCY AI — Face Swap Backend
FastAPI server: static face swap, live WebSocket swap, avatar catalogue,
and voice transform endpoint.
"""

import asyncio
import base64
import io
import json
import os
import contextlib
import pathlib
from typing import Optional

import cv2
import httpx
import numpy as np
import soundfile as sf
import librosa

from insightface.app import FaceAnalysis

from fastapi import (
    FastAPI, File, Form, HTTPException, Response,
    UploadFile, WebSocket, WebSocketDisconnect,
)
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, JSONResponse
from fastapi.staticfiles import StaticFiles

# ─────────────────────────────────────────────────────────────────────────────
#  Paths
# ─────────────────────────────────────────────────────────────────────────────
_HERE          = pathlib.Path(__file__).parent
_AVATAR_CACHE  = _HERE / "avatars_cache"
_AVATAR_CACHE.mkdir(exist_ok=True)

_INSWAPPER_PATH = str(_HERE / "models" / "models" / "inswapper_128.onnx")
_CASCADE_PATH   = cv2.data.haarcascades + "haarcascade_frontalface_default.xml"

# ─────────────────────────────────────────────────────────────────────────────
#  Avatar catalogue — 10 SD-generated diverse AI portraits.
#  Files live in avatars_cache/{id}.jpg, generated by generate_avatars.py
# ─────────────────────────────────────────────────────────────────────────────
_AVATARS = [
    # Female
    {"id": "gen_f_01", "name": "Aria",   "category": "Women",
     "ethnicity": "European",     "gender": "female",
     "voice_ref": "en_default_female"},
    {"id": "gen_f_02", "name": "Anaya",  "category": "Women",
     "ethnicity": "South Asian",  "gender": "female",
     "voice_ref": "en_default_female"},
    {"id": "gen_f_03", "name": "Zara",   "category": "Women",
     "ethnicity": "African",      "gender": "female",
     "voice_ref": "en_default_female"},
    {"id": "gen_f_04", "name": "Mei",    "category": "Women",
     "ethnicity": "East Asian",   "gender": "female",
     "voice_ref": "en_default_female"},
    {"id": "gen_f_05", "name": "Sofia",  "category": "Women",
     "ethnicity": "Hispanic",     "gender": "female",
     "voice_ref": "en_default_female"},
    # Male
    {"id": "gen_m_01", "name": "Lucas",  "category": "Men",
     "ethnicity": "European",     "gender": "male",
     "voice_ref": "en_default_male"},
    {"id": "gen_m_02", "name": "Kai",    "category": "Men",
     "ethnicity": "Middle Eastern","gender": "male",
     "voice_ref": "en_default_male"},
    {"id": "gen_m_03", "name": "Malik",  "category": "Men",
     "ethnicity": "African",      "gender": "male",
     "voice_ref": "en_default_male"},
    {"id": "gen_m_04", "name": "Ren",    "category": "Men",
     "ethnicity": "East Asian",   "gender": "male",
     "voice_ref": "en_default_male"},
    {"id": "gen_m_05", "name": "Diego",  "category": "Men",
     "ethnicity": "Hispanic",     "gender": "male",
     "voice_ref": "en_default_male"},
]
_AVATAR_MAP = {a["id"]: a for a in _AVATARS}

# ─────────────────────────────────────────────────────────────────────────────
#  Voice FX map (Tone.js fallback when OpenVoice not loaded)
# ─────────────────────────────────────────────────────────────────────────────
_VOICE_FX: dict[str, dict] = {
    # Bigger pitch deltas so the avatar voice is clearly different from yours
    # but still natural — librosa pitch_shift handles ±6 semitones cleanly.
    "gen_f": {"semitones":  4, "effect": None},
    "gen_m": {"semitones": -4, "effect": None},
}

# ─────────────────────────────────────────────────────────────────────────────
#  Global model references
# ─────────────────────────────────────────────────────────────────────────────
_face_app:     Optional[FaceAnalysis] = None   # full pipeline — used ONCE per session on the source avatar
_face_app_fast:Optional[FaceAnalysis] = None   # detection + landmarks only — per-frame target detection
_inswapper                            = None
_inswap_emap:  Optional[np.ndarray]   = None   # 512x512 embedding map baked into the inswapper ONNX
_haar_cascade                         = None
_gfpgan                               = None   # GFPGANer for face enhancement (optional)
_wav2lip                              = None   # Wav2LipONNX for audio-driven lip-sync (optional)
_WAV2LIP_PATH                          = str(_HERE / "models" / "models" / "wav2lip_gan.onnx")
_face_parser                          = None   # BiSeNet face-parser ONNX for hair swap (optional)
_FACE_PARSER_PATH                      = str(_HERE / "models" / "models" / "face_parser.onnx")


def _load_models() -> None:
    """Load InsightFace FaceAnalysis, inswapper (+ emap), and Haar cascade."""
    global _face_app, _face_app_fast, _inswapper, _inswap_emap, _haar_cascade

    # Full pipeline (detection + landmarks + ArcFace + gender/age) — used ONCE
    # per session when the source avatar is loaded so we can extract its
    # 512-d normed_embedding for the inswapper source latent.
    _face_app = FaceAnalysis(name="buffalo_l", providers=["CUDAExecutionProvider", "CPUExecutionProvider"])
    _face_app.prepare(ctx_id=0, det_thresh=0.3, det_size=(640, 640))

    # Per-frame target detection — also high res for accurate keypoints
    # (which determine warp quality). Recognition/genderage stripped because
    # they're truly unused for target frames.
    _face_app_fast = FaceAnalysis(name="buffalo_l", providers=["CUDAExecutionProvider", "CPUExecutionProvider"])
    _face_app_fast.prepare(ctx_id=0, det_thresh=0.3, det_size=(480, 480))
    for mod in ("recognition", "genderage"):
        if mod in _face_app_fast.models:
            del _face_app_fast.models[mod]

    # inswapper_128 ONNX
    import onnxruntime as ort
    sess_opts = ort.SessionOptions()
    sess_opts.graph_optimization_level = ort.GraphOptimizationLevel.ORT_ENABLE_ALL
    _inswapper = ort.InferenceSession(
        _INSWAPPER_PATH,
        sess_options=sess_opts,
        providers=["CUDAExecutionProvider", "CPUExecutionProvider"],
    )

    # CRITICAL: inswapper_128 needs the source embedding mapped through an "emap"
    # (512x512 matrix baked into the ONNX as the last initializer) before passing
    # it as the source latent. Without this step the swap produces garbage / no-op.
    import onnx
    from onnx.numpy_helper import to_array
    _model_proto = onnx.load(_INSWAPPER_PATH)
    _inswap_emap = to_array(_model_proto.graph.initializer[-1]).astype(np.float32)
    print(f"[LUCY] inswapper emap loaded: shape={_inswap_emap.shape}")

    # Haar cascade (fallback detector)
    _haar_cascade = cv2.CascadeClassifier(_CASCADE_PATH)

    # Wav2Lip — audio-driven lip sync. Generates a video of an avatar face
    # speaking with mouth movements matching the input audio. Optional;
    # only loads if the model file is present.
    global _wav2lip
    try:
        from wav2lip import Wav2LipONNX
        if pathlib.Path(_WAV2LIP_PATH).exists():
            _wav2lip = Wav2LipONNX(_WAV2LIP_PATH)
            print(f"[LUCY] Wav2Lip ONNX loaded — audio-driven lip sync ENABLED")
        else:
            print(f"[LUCY] Wav2Lip model not found at {_WAV2LIP_PATH} — lip sync DISABLED. "
                  f"Download wav2lip_gan.onnx and place it in models/models/")
    except Exception as e:
        _wav2lip = None
        print(f"[LUCY] Wav2Lip load failed ({type(e).__name__}: {e}) — lip sync DISABLED")

    # BiSeNet face parser — for proper hair swap. Optional.
    global _face_parser
    try:
        from face_parser import FaceParserONNX
        if pathlib.Path(_FACE_PARSER_PATH).exists():
            _face_parser = FaceParserONNX(_FACE_PARSER_PATH)
            print(f"[LUCY] BiSeNet face parser loaded — HAIR SWAP enabled")
        else:
            print(f"[LUCY] face_parser.onnx not found at {_FACE_PARSER_PATH} — hair swap DISABLED.")
    except Exception as e:
        _face_parser = None
        print(f"[LUCY] face parser load failed ({type(e).__name__}: {e}) — hair swap DISABLED")

    # GFPGAN v1.4 — face restoration on the swap output (sharpens identity,
    # fixes the inherent softness of inswapper_128). ~333MB, auto-downloads
    # to ~/.gfpgan/weights/. Adds ~80-120ms per frame on A10G.
    global _gfpgan
    try:
        from gfpgan import GFPGANer
        gfpgan_model_path = "https://github.com/TencentARC/GFPGAN/releases/download/v1.3.4/GFPGANv1.4.pth"
        _gfpgan = GFPGANer(
            model_path=gfpgan_model_path,
            upscale=1,
            arch="clean",
            channel_multiplier=2,
            bg_upsampler=None,
        )
        print("[LUCY] GFPGAN v1.4 loaded — face enhancement ENABLED")
    except Exception as e:
        _gfpgan = None
        print(f"[LUCY] GFPGAN not loaded ({type(e).__name__}: {e}) — running WITHOUT face enhancement. "
              f"Install with: pip install gfpgan")

    print("[LUCY] Models loaded: FaceAnalysis buffalo_l + inswapper_128 + Haar cascade"
          f"{' + GFPGAN' if _gfpgan else ''}")


# ─────────────────────────────────────────────────────────────────────────────
#  Face detection helpers
# ─────────────────────────────────────────────────────────────────────────────
def _largest_face(faces):
    """Return the face with the largest bounding box area, or None."""
    if not faces:
        return None
    return max(faces, key=lambda f: (f.bbox[2] - f.bbox[0]) * (f.bbox[3] - f.bbox[1]))


def _haar_detect(img_bgr: np.ndarray):
    """Haar cascade fallback — returns (x, y, w, h) or None."""
    gray = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2GRAY)
    faces = _haar_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=4, minSize=(30, 30))
    if len(faces) == 0:
        return None
    # Largest by area
    faces = sorted(faces, key=lambda r: r[2] * r[3], reverse=True)
    return faces[0]  # (x, y, w, h)


def _detect(img_bgr: np.ndarray):
    """Detect faces — returns (face_obj, kps, bbox, is_real) 4-tuple for live caching."""
    faces = _face_app.get(img_bgr)
    if faces:
        f = _largest_face(faces)
        return f, getattr(f, 'kps', None), f.bbox, True
    haar = _haar_detect(img_bgr)
    if haar is not None:
        x, y, w, h = haar
        bbox = np.array([x, y, x + w, y + h], dtype=np.float32)
        return haar, None, bbox, False
    return None, None, None, False




# ─────────────────────────────────────────────────────────────────────────────
#  Head / hair mask
# ─────────────────────────────────────────────────────────────────────────────
def _head_fg_mask(img: np.ndarray, face_bbox) -> np.ndarray:
    """
    Build a binary mask covering the head + hair region.

    1. Guaranteed oval base — never returns an all-zero mask.
    2. 2-pass GrabCut enhancement when the face bbox is reliable.
    """
    h, w = img.shape[:2]
    mask = np.zeros((h, w), np.uint8)

    # ── Step 1: guaranteed oval base ────────────────────────────────────────
    x1, y1, x2, y2 = (int(v) for v in face_bbox[:4])
    fx, fy = (x1 + x2) // 2, (y1 + y2) // 2   # face centre
    fw, fh = x2 - x1, y2 - y1                    # face dimensions

    # Oval that covers face + hair above + slight width padding
    ell_cx, ell_cy = fx, fy - int(fh * 0.15)
    ell_rx = int(fw * 0.62)
    ell_ry = int(fh * 0.88)
    ell_cx = np.clip(ell_cx, ell_rx, w - ell_rx)
    ell_cy = np.clip(ell_cy, ell_ry, h - ell_ry)
    cv2.ellipse(mask, (ell_cx, ell_cy), (ell_rx, ell_ry), 0, 0, 360, 255, -1)

    # ── Step 2: GrabCut enhancement ─────────────────────────────────────────
    try:
        pad_x = int(fw * 1.2)
        pad_y = int(fh * 1.6)
        rx1 = max(0, x1 - pad_x)
        ry1 = max(0, y1 - pad_y)
        rx2 = min(w, x2 + pad_x)
        ry2 = min(h, y2 + int(fh * 0.4))
        roi_w, roi_h = rx2 - rx1, ry2 - ry1
        if roi_w > 10 and roi_h > 10:
            gc_mask = np.zeros((h, w), np.uint8)
            rect = (rx1, ry1, roi_w, roi_h)
            bgd = np.zeros((1, 65), np.float64)
            fgd = np.zeros((1, 65), np.float64)
            cv2.grabCut(img, gc_mask, rect, bgd, fgd, 3, cv2.GC_INIT_WITH_RECT)
            fg = np.where((gc_mask == cv2.GC_FGD) | (gc_mask == cv2.GC_PR_FGD), 255, 0).astype(np.uint8)
            # Combine: keep oval base union GrabCut result
            mask = cv2.bitwise_or(mask, fg)
    except Exception:
        pass  # GrabCut can fail on degenerate inputs — oval base is sufficient

    # Smooth edges
    mask = cv2.GaussianBlur(mask, (21, 21), 0)
    _, mask = cv2.threshold(mask, 127, 255, cv2.THRESH_BINARY)
    return mask


# ─────────────────────────────────────────────────────────────────────────────
#  Style helpers
# ─────────────────────────────────────────────────────────────────────────────
def _is_cartoon(img: np.ndarray) -> bool:
    """Heuristic: cartoon/anime images have lower edge density."""
    gray  = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    edges = cv2.Canny(gray, 100, 200)
    density = np.count_nonzero(edges) / edges.size
    return density < 0.04


def _color_transfer(src: np.ndarray, tgt: np.ndarray) -> np.ndarray:
    """Transfer mean+std colour statistics from src to tgt in LAB space."""
    src_lab = cv2.cvtColor(src, cv2.COLOR_BGR2LAB).astype(np.float32)
    tgt_lab = cv2.cvtColor(tgt, cv2.COLOR_BGR2LAB).astype(np.float32)
    for c in range(3):
        sm, ss = src_lab[:, :, c].mean(), src_lab[:, :, c].std()
        tm, ts = tgt_lab[:, :, c].mean(), tgt_lab[:, :, c].std()
        if ts > 1e-6:
            tgt_lab[:, :, c] = (tgt_lab[:, :, c] - tm) * (ss / ts) + sm
    tgt_lab = np.clip(tgt_lab, 0, 255).astype(np.uint8)
    return cv2.cvtColor(tgt_lab, cv2.COLOR_LAB2BGR)


# ─────────────────────────────────────────────────────────────────────────────
#  Swap implementations
# ─────────────────────────────────────────────────────────────────────────────
def _run_inswapper(src_face, tgt_face, tgt_img: np.ndarray) -> np.ndarray:
    """Single inswapper pass — returns the modified target image.

    Inswapper_128 ONNX interface:
      • input 'target': warped target face patch (1, 3, 128, 128) in RGB [0,1]
      • input 'source': source identity embedding (1, 512) — normed
      • output:         modified target face (1, 3, 128, 128) in RGB [0,1]
    We feed the SOURCE face's normed_embedding so the target patch
    inherits the source identity.
    """
    in_names  = [i.name for i in _inswapper.get_inputs()]
    out_names = [o.name for o in _inswapper.get_outputs()]

    # Source latent: embedding @ emap, then L2-normalize. This is the official
    # InsightFace inswapper recipe — without the emap projection the model
    # outputs ~the original face (effectively a no-op swap).
    src_embed = src_face.normed_embedding.reshape(1, -1).astype(np.float32)
    latent    = src_embed @ _inswap_emap
    latent    = latent / (np.linalg.norm(latent) + 1e-9)
    blob      = latent.astype(np.float32)

    # Warp target face patch to 128×128 ArcFace template
    kps = tgt_face.kps
    M = cv2.estimateAffinePartial2D(kps, _get_arcface_template(128))[0]
    face_patch = cv2.warpAffine(tgt_img, M, (128, 128), flags=cv2.INTER_LINEAR)
    face_patch_f = (face_patch.astype(np.float32) / 255.0)
    face_patch_f = face_patch_f[:, :, ::-1]  # BGR→RGB
    face_patch_f = face_patch_f.transpose(2, 0, 1)[np.newaxis]

    result_patch = _inswapper.run(
        out_names,
        {in_names[0]: face_patch_f, in_names[1]: blob},
    )[0][0]

    result_patch = result_patch.transpose(1, 2, 0)[:, :, ::-1]  # RGB→BGR
    result_patch = (np.clip(result_patch, 0, 1) * 255).astype(np.uint8)

    # Unsharp + cubic upscale — back to quality settings. Counters
    # inswapper's soft 128px output for sharper face details.
    gauss = cv2.GaussianBlur(result_patch, (0, 0), sigmaX=1.2)
    result_patch = cv2.addWeighted(result_patch, 1.5, gauss, -0.5, 0)

    M_inv = cv2.invertAffineTransform(M)
    patch_back = cv2.warpAffine(result_patch, M_inv, (tgt_img.shape[1], tgt_img.shape[0]),
                                flags=cv2.INTER_CUBIC)

    ih, iw = tgt_img.shape[:2]
    x1, y1, x2, y2 = (int(v) for v in tgt_face.bbox)
    fw, fh = x2 - x1, y2 - y1
    cx, cy = (x1 + x2) // 2, (y1 + y2) // 2

    # Precise face mask from the 106 facial landmarks InsightFace already
    # detected — convex hull = natural face outline (jaw → cheek → temple).
    # Eliminates the obvious 'cut and paste' look an ellipse causes around
    # the chin and jawline. Falls back to the old ellipse only if landmarks
    # aren't available.
    lmk = getattr(tgt_face, "landmark_2d_106", None)
    blend_mask = np.zeros((ih, iw), np.uint8)
    if lmk is not None and len(lmk) > 10:
        pts = lmk.astype(np.int32)
        # Extend each landmark slightly outward from the face centroid so the
        # hull covers a tiny bit of background — Poisson softens the rest.
        center = np.array([cx, cy], dtype=np.float32)
        expanded = (pts.astype(np.float32) - center) * 1.06 + center
        hull = cv2.convexHull(expanded.astype(np.int32))
        cv2.fillPoly(blend_mask, [hull], 255)
        # Tiny smoothing pass on the edges
        blend_mask = cv2.GaussianBlur(blend_mask, (15, 15), 0)
        _, blend_mask = cv2.threshold(blend_mask, 100, 255, cv2.THRESH_BINARY)
        # Centre of mass for Poisson
        M_m = cv2.moments(blend_mask)
        if M_m["m00"] > 0:
            poisson_cx = int(M_m["m10"] / M_m["m00"])
            poisson_cy = int(M_m["m01"] / M_m["m00"])
        else:
            poisson_cx, poisson_cy = cx, cy
    else:
        # Fallback ellipse (forehead-extended) if landmarks missing
        oval_cy = max(1, cy - int(fh * 0.08))
        oval_rx = max(1, int(fw * 0.54))
        oval_ry = max(1, int(fh * 0.62))
        oval_cy = int(np.clip(oval_cy, oval_ry + 1, ih - oval_ry - 1))
        ecx     = int(np.clip(cx,      oval_rx + 1, iw - oval_rx - 1))
        cv2.ellipse(blend_mask, (ecx, oval_cy), (oval_rx, oval_ry), 0, 0, 360, 255, -1)
        poisson_cx, poisson_cy = ecx, oval_cy

    # Poisson seamless clone — gradients match at the mask boundary so the
    # face flows into the surrounding skin with no visible seam.
    try:
        swapped = cv2.seamlessClone(patch_back, tgt_img, blend_mask,
                                    (poisson_cx, poisson_cy), cv2.NORMAL_CLONE)
    except cv2.error:
        bm = cv2.GaussianBlur(blend_mask, (41, 41), 0)
        alpha = bm[:, :, np.newaxis].astype(np.float32) / 255.0
        swapped = (patch_back.astype(np.float32) * alpha +
                   tgt_img.astype(np.float32) * (1 - alpha)).astype(np.uint8)

    # ── GFPGAN face enhancement (if loaded) ──────────────────────────────────
    # Restores fine detail lost by inswapper_128's low-resolution output.
    # weight=0.5 blends 50% restored / 50% original — pure restoration can
    # erase identity (over-smooth). Catches errors so a single bad frame
    # doesn't break the whole pipeline.
    if _gfpgan is not None:
        try:
            _, _, restored = _gfpgan.enhance(
                swapped,
                has_aligned=False,
                only_center_face=True,
                paste_back=True,
                weight=0.5,
            )
            if restored is not None:
                swapped = restored
        except Exception:
            pass

    return swapped


_ARCFACE_DST = np.array([
    [38.2946, 51.6963],
    [73.5318, 51.5014],
    [56.0252, 71.7366],
    [41.5493, 92.3655],
    [70.7299, 92.2041],
], dtype=np.float32)


def _get_arcface_template(size: int) -> np.ndarray:
    scale = size / 112.0
    return _ARCFACE_DST * scale


def _swap_real(src_img: np.ndarray, tgt_img: np.ndarray) -> np.ndarray:
    """
    Real-face swap:
      1. inswapper on face region
      2. SeamlessClone head+hair oval back onto original target
    """
    src_faces = _face_app.get(src_img)
    tgt_faces = _face_app.get(tgt_img)
    src_face  = _largest_face(src_faces)
    tgt_face  = _largest_face(tgt_faces)
    if src_face is None or tgt_face is None:
        raise ValueError("Could not detect face in source or target image")

    # Step 1 — inswapper
    swapped = _run_inswapper(src_face, tgt_face, tgt_img)

    # Step 2 — hair oval seamlessClone to bring hair from swapped→tgt
    hair_mask = _head_fg_mask(swapped, tgt_face.bbox)
    # Centre of mass of mask for seamlessClone
    M = cv2.moments(hair_mask)
    if M["m00"] > 0:
        cX = int(M["m10"] / M["m00"])
        cY = int(M["m01"] / M["m00"])
    else:
        x1, y1, x2, y2 = (int(v) for v in tgt_face.bbox)
        cX, cY = (x1 + x2) // 2, (y1 + y2) // 2
    try:
        result = cv2.seamlessClone(swapped, tgt_img, hair_mask, (cX, cY), cv2.NORMAL_CLONE)
    except cv2.error:
        result = swapped  # fallback: seamlessClone failed, keep inswapper result
    return result


def _swap_geometric(src_img: np.ndarray, tgt_img: np.ndarray) -> np.ndarray:
    """
    Cartoon/anime swap:
      - Strip background corners to avoid artefacts
      - Colour transfer for style adaptation
      - Single seamlessClone with full head+hair mask
    """
    src_faces = _face_app.get(src_img)
    tgt_faces = _face_app.get(tgt_img)
    src_face  = _largest_face(src_faces)
    tgt_face  = _largest_face(tgt_faces)
    if src_face is None or tgt_face is None:
        raise ValueError("Could not detect face in source or target image")

    # Colour-match source to target palette
    src_adapted = _color_transfer(tgt_img, src_img)

    # Resize source to match target face scale
    sx1, sy1, sx2, sy2 = (int(v) for v in src_face.bbox)
    tx1, ty1, tx2, ty2 = (int(v) for v in tgt_face.bbox)
    scale = max((tx2 - tx1) / max(sx2 - sx1, 1), (ty2 - ty1) / max(sy2 - sy1, 1))
    new_w = int(src_img.shape[1] * scale)
    new_h = int(src_img.shape[0] * scale)
    src_resized = cv2.resize(src_adapted, (new_w, new_h), interpolation=cv2.INTER_LANCZOS4)

    # Detect face in resized source
    src_r_faces = _face_app.get(src_resized)
    src_r_face  = _largest_face(src_r_faces)
    if src_r_face is None:
        src_r_face = src_face  # fallback

    # Build composite: paste resized source face region onto target
    canvas = tgt_img.copy()
    sr_x1, sr_y1, sr_x2, sr_y2 = (int(v) for v in src_r_face.bbox)
    patch_w, patch_h = sr_x2 - sr_x1, sr_y2 - sr_y1
    tcx, tcy = (tx1 + tx2) // 2, (ty1 + ty2) // 2
    dst_x1 = max(0, tcx - patch_w // 2)
    dst_y1 = max(0, tcy - patch_h // 2)
    dst_x2 = min(canvas.shape[1], dst_x1 + patch_w)
    dst_y2 = min(canvas.shape[0], dst_y1 + patch_h)
    act_w, act_h = dst_x2 - dst_x1, dst_y2 - dst_y1
    patch = src_resized[sr_y1:sr_y1 + act_h, sr_x1:sr_x1 + act_w]
    canvas[dst_y1:dst_y2, dst_x1:dst_x2] = patch

    # Head+hair mask for seamlessClone
    face_bbox_for_mask = [dst_x1, dst_y1, dst_x2, dst_y2]
    head_mask = _head_fg_mask(canvas, face_bbox_for_mask)
    M = cv2.moments(head_mask)
    if M["m00"] > 0:
        cX = int(M["m10"] / M["m00"])
        cY = int(M["m01"] / M["m00"])
    else:
        cX, cY = tcx, tcy
    try:
        result = cv2.seamlessClone(canvas, tgt_img, head_mask, (cX, cY), cv2.MIXED_CLONE)
    except cv2.error:
        result = canvas
    return result


def _swap(src_img: np.ndarray, tgt_img: np.ndarray) -> np.ndarray:
    """Dispatcher: cartoon → _swap_geometric, real → _swap_real."""
    if _is_cartoon(src_img):
        return _swap_geometric(src_img, tgt_img)
    return _swap_real(src_img, tgt_img)


def _color_correct_face(swapped: np.ndarray, target: np.ndarray, bbox) -> np.ndarray:
    """Reinhard-style LAB-space color transfer: match swapped face's mean/std
    (per channel) to the target face region. Much better skin tone match
    than simple per-channel brightness scaling — preserves saturation
    relationships and handles cross-ethnicity swaps cleanly."""
    x1, y1, x2, y2 = [int(v) for v in bbox]
    x1, y1 = max(0, x1), max(0, y1)
    x2, y2 = min(swapped.shape[1], x2), min(swapped.shape[0], y2)
    if x2 <= x1 or y2 <= y1:
        return swapped
    sw_patch  = swapped[y1:y2, x1:x2]
    tgt_patch = target[y1:y2, x1:x2]
    if sw_patch.size == 0 or tgt_patch.size == 0:
        return swapped

    sw_lab  = cv2.cvtColor(sw_patch,  cv2.COLOR_BGR2LAB).astype(np.float32)
    tgt_lab = cv2.cvtColor(tgt_patch, cv2.COLOR_BGR2LAB).astype(np.float32)
    out = sw_lab.copy()
    # Per-channel blend. Luminance (L) and chromaticity (a, b) are weighted
    # differently — a strong 'a'/'b' transfer locks skin tone (cross-ethnicity
    # swaps no longer look fair-on-dark); a softer 'L' transfer preserves
    # the avatar's facial detail/shading.
    blends = (0.65, 0.95, 0.95)
    for c in range(3):
        sm, ss = sw_lab[:, :, c].mean(),  sw_lab[:, :, c].std() + 1e-6
        tm, ts = tgt_lab[:, :, c].mean(), tgt_lab[:, :, c].std() + 1e-6
        adjusted = (sw_lab[:, :, c] - sm) * (ts / ss) + tm
        out[:, :, c] = blends[c] * adjusted + (1 - blends[c]) * sw_lab[:, :, c]
    out = np.clip(out, 0, 255).astype(np.uint8)
    out_bgr = cv2.cvtColor(out, cv2.COLOR_LAB2BGR)

    result = swapped.copy()
    result[y1:y2, x1:x2] = out_bgr
    return result


def _swap_live(src_img: np.ndarray, src_detection, target_img: np.ndarray):
    """
    Fast live swap with cached src_detection.
    Real faces: inswapper + color correction + feathered boundary.
    Cartoon:    geometric warp.
    """
    src_face, src_kps, src_bbox, src_real = src_detection
    # Use the stripped-down detector for per-frame target — ~3x faster
    tgt_faces = _face_app_fast.get(target_img)
    tgt_face  = _largest_face(tgt_faces)
    if src_face is None or tgt_face is None:
        return None

    if src_real and tgt_face is not None:
        # Identity transfer (avatar face on user's head/body)
        result = _run_inswapper(src_face, tgt_face, target_img)
        # LAB skin-tone match — back on. ~10 ms / frame but materially
        # improves how the swapped face blends into the user's neck/body.
        result = _color_correct_face(result, target_img, tgt_face.bbox)
        return result

    # Cartoon source
    try: return _swap_geometric(src_img, target_img)
    except: return None


def _do_swap(src_img: np.ndarray, frame: np.ndarray) -> Optional[np.ndarray]:
    """
    Fast swap for WebSocket live path.
    For real faces: inswapper only (no seamlessClone hair pass) for speed.
    For cartoon: full geometric swap.
    """
    if _is_cartoon(src_img):
        try:
            return _swap_geometric(src_img, frame)
        except Exception:
            return None

    src_faces = _face_app.get(src_img)
    tgt_faces = _face_app.get(frame)
    src_face  = _largest_face(src_faces)
    tgt_face  = _largest_face(tgt_faces)
    if src_face is None or tgt_face is None:
        return None
    try:
        return _run_inswapper(src_face, tgt_face, frame)
    except Exception:
        return None


# ─────────────────────────────────────────────────────────────────────────────
#  Voice transform helpers
# ─────────────────────────────────────────────────────────────────────────────
def _apply_robot(y: np.ndarray, sr: int) -> np.ndarray:
    """Amplitude modulation at 80 Hz — classic robot effect."""
    t = np.arange(len(y)) / sr
    carrier = np.sin(2 * np.pi * 80 * t)
    return (y * carrier).astype(np.float32)


def _apply_echo(y: np.ndarray, sr: int) -> np.ndarray:
    """Two-tap echo: 80 ms delay at 0.45 gain + 160 ms at 0.20 gain."""
    delay1 = int(0.080 * sr)  # 80 ms
    delay2 = int(0.160 * sr)  # 160 ms
    out = y.copy()
    if delay1 < len(y):
        out[delay1:] += 0.45 * y[: len(y) - delay1]
    if delay2 < len(y):
        out[delay2:] += 0.20 * y[: len(y) - delay2]
    # Normalise to avoid clipping
    peak = np.max(np.abs(out))
    if peak > 1.0:
        out /= peak
    return out.astype(np.float32)


def _transform_voice(audio_bytes: bytes, avatar_id: str) -> bytes:
    """
    Load audio → pitch shift → optional effect → encode WAV → return bytes.

    Audio is expected to be a WAV blob (browser pre-encodes via WebAudio).
    Falls back to librosa-direct (handles raw PCM, ogg, etc.) if soundfile
    can't open it.
    """
    # FX prefix lookup (longest first)
    fx_params = {"semitones": 0, "effect": None}
    for prefix in sorted(_VOICE_FX.keys(), key=len, reverse=True):
        if avatar_id.startswith(prefix):
            fx_params = _VOICE_FX[prefix]
            break

    # Try soundfile first (handles WAV natively, no external deps)
    try:
        buf = io.BytesIO(audio_bytes)
        y, sr = sf.read(buf, dtype="float32")
        if y.ndim > 1:
            y = y.mean(axis=1)
    except Exception:
        # Last resort — librosa via audioread (may need ffmpeg for webm/ogg)
        buf = io.BytesIO(audio_bytes)
        y, sr = librosa.load(buf, sr=None, mono=True)

    # Pitch shift
    semitones = fx_params["semitones"]
    if semitones != 0:
        y = librosa.effects.pitch_shift(y, sr=sr, n_steps=semitones)

    # Effect
    effect = fx_params.get("effect")
    if effect == "robot":
        y = _apply_robot(y, sr)
    elif effect == "echo":
        y = _apply_echo(y, sr)

    # Encode to WAV in memory
    out_buf = io.BytesIO()
    sf.write(out_buf, y, sr, format="WAV", subtype="PCM_16")
    out_buf.seek(0)
    return out_buf.read()


# ─────────────────────────────────────────────────────────────────────────────
#  FastAPI app — lifespan
# ─────────────────────────────────────────────────────────────────────────────
@contextlib.asynccontextmanager
async def lifespan(app: FastAPI):
    # Load models on startup (runs once in the main process)
    loop = asyncio.get_event_loop()
    await loop.run_in_executor(None, _load_models)
    yield
    # Cleanup (nothing to do for now)


app = FastAPI(title="LUCY AI Face Swap Backend", version="1.0.0", lifespan=lifespan)

# Serve demo UI at http://<host>:7860/
app.mount("/demo", StaticFiles(directory=str(_HERE.parent / "demo"), html=True), name="demo")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ─────────────────────────────────────────────────────────────────────────────
#  Utility: decode uploaded image bytes
# ─────────────────────────────────────────────────────────────────────────────
def _decode_image(data: bytes) -> np.ndarray:
    arr = np.frombuffer(data, np.uint8)
    img = cv2.imdecode(arr, cv2.IMREAD_COLOR)
    if img is None:
        raise HTTPException(status_code=400, detail="Could not decode image")
    return img


def _encode_jpeg(img: np.ndarray, quality: int = 92) -> bytes:
    ok, buf = cv2.imencode(".jpg", img, [cv2.IMWRITE_JPEG_QUALITY, quality])
    if not ok:
        raise RuntimeError("JPEG encode failed")
    return buf.tobytes()


# ─────────────────────────────────────────────────────────────────────────────
#  Routes
# ─────────────────────────────────────────────────────────────────────────────

@app.get("/health")
async def health():
    return {"status": "ok", "models_loaded": _inswapper is not None}


@app.post("/face-swap")
async def face_swap(
    source: UploadFile = File(...),
    target: UploadFile = File(...),
):
    """Static face swap — returns JPEG image."""
    src_bytes = await source.read()
    tgt_bytes = await target.read()
    src_img = _decode_image(src_bytes)
    tgt_img = _decode_image(tgt_bytes)

    loop = asyncio.get_event_loop()
    try:
        result = await loop.run_in_executor(None, _swap, src_img, tgt_img)
    except ValueError as e:
        raise HTTPException(status_code=422, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Swap failed: {e}")

    return Response(content=_encode_jpeg(result), media_type="image/jpeg")


@app.get("/avatars")
async def list_avatars():
    """Return avatar catalogue."""
    avatars_out = [
        {
            "id":        a["id"],
            "name":      a["name"],
            "category":  a["category"],
            "image_url": f"/avatars/{a['id']}/image",
        }
        for a in _AVATARS
    ]
    return {"avatars": avatars_out}


@app.get("/avatars/{avatar_id}/image")
async def get_avatar_image(avatar_id: str):
    """Serve a generated AI avatar from disk."""
    if avatar_id not in _AVATAR_MAP:
        raise HTTPException(status_code=404, detail="Avatar not found")

    cache_path = _AVATAR_CACHE / f"{avatar_id}.jpg"
    if not cache_path.exists():
        raise HTTPException(
            status_code=404,
            detail=f"Avatar image not generated yet. Run "
                   f"`python generate_avatars.py` in face_swap_backend/.",
        )
    return FileResponse(str(cache_path), media_type="image/jpeg")


@app.post("/face-swap/with-avatar")
async def face_swap_with_avatar(
    target:    UploadFile = File(...),
    avatar_id: str        = Form(...),
):
    """Swap target face with a catalogue avatar."""
    if avatar_id not in _AVATAR_MAP:
        raise HTTPException(status_code=404, detail="Avatar not found")

    cache_path = _AVATAR_CACHE / f"{avatar_id}.jpg"
    if not cache_path.exists():
        raise HTTPException(
            status_code=404,
            detail="Avatar image not generated yet. Run generate_avatars.py.",
        )

    src_img = _decode_image(cache_path.read_bytes())
    tgt_img = _decode_image(await target.read())

    loop = asyncio.get_event_loop()
    try:
        result = await loop.run_in_executor(None, _swap, src_img, tgt_img)
    except ValueError as e:
        raise HTTPException(status_code=422, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Swap failed: {e}")

    return Response(content=_encode_jpeg(result), media_type="image/jpeg")


# ─────────────────────────────────────────────────────────────────────────────
#  Voice transform endpoint
# ─────────────────────────────────────────────────────────────────────────────
@app.post("/voice/transform")
async def voice_transform(
    audio:     UploadFile = File(...),
    avatar_id: str        = Form(...),
):
    """
    Accept a browser audio recording (webm/ogg) and an avatar_id.
    Apply pitch shift + optional effect, return transformed WAV.
    """
    if avatar_id not in _AVATAR_MAP:
        raise HTTPException(status_code=404, detail=f"Unknown avatar_id: {avatar_id}")

    audio_bytes = await audio.read()
    if not audio_bytes:
        raise HTTPException(status_code=400, detail="Empty audio upload")

    loop = asyncio.get_event_loop()
    try:
        wav_bytes = await loop.run_in_executor(None, _transform_voice, audio_bytes, avatar_id)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Voice transform failed: {e}")

    return Response(content=wav_bytes, media_type="audio/wav")


# ─────────────────────────────────────────────────────────────────────────────
#  Wav2Lip — audio-driven lip-sync video generation
# ─────────────────────────────────────────────────────────────────────────────
def _lipsync_generate(wav_bytes: bytes, avatar_id: str) -> bytes:
    """
    Build a lip-synced MP4 of the avatar speaking the transformed audio.
    Returns raw MP4 bytes.
    """
    if _wav2lip is None:
        raise RuntimeError("Wav2Lip not loaded — drop wav2lip_gan.onnx into models/models/")

    import io
    # Decode WAV → mono float32 @ 16 kHz
    y, sr = sf.read(io.BytesIO(wav_bytes), dtype="float32")
    if y.ndim > 1:
        y = y.mean(axis=1)
    if sr != 16000:
        y = librosa.resample(y, orig_sr=sr, target_sr=16000)
        sr = 16000

    # Load avatar + detect face
    avatar_path = _AVATAR_CACHE / f"{avatar_id}.jpg"
    if not avatar_path.exists():
        raise RuntimeError(f"Avatar image missing for {avatar_id}")
    avatar_img = _decode_image(avatar_path.read_bytes())
    src_faces  = _face_app.get(avatar_img)
    src_face   = _largest_face(src_faces)
    if src_face is None:
        raise RuntimeError("No face detected in avatar image")

    frames = _wav2lip.generate(
        avatar_img, y, audio_sr=sr,
        face_bbox=tuple(int(v) for v in src_face.bbox),
    )

    # Encode frames + audio to MP4 using imageio-ffmpeg (bundled binary).
    # ffmpeg.exe isn't required on the host; imageio-ffmpeg ships its own.
    import tempfile, subprocess, os, shutil
    tmpdir = tempfile.mkdtemp(prefix="lucy_lip_")
    try:
        # Save audio WAV
        wav_out = os.path.join(tmpdir, "audio.wav")
        sf.write(wav_out, y, sr, format="WAV", subtype="PCM_16")

        # Save frames as PNGs
        for i, f in enumerate(frames):
            cv2.imwrite(os.path.join(tmpdir, f"frame_{i:05d}.png"), f)

        # Use imageio_ffmpeg's bundled binary
        try:
            import imageio_ffmpeg
            ff = imageio_ffmpeg.get_ffmpeg_exe()
        except Exception:
            ff = "ffmpeg"

        out_path = os.path.join(tmpdir, "out.mp4")
        cmd = [
            ff, "-y",
            "-framerate", "25",
            "-i", os.path.join(tmpdir, "frame_%05d.png"),
            "-i", wav_out,
            "-c:v", "libx264", "-pix_fmt", "yuv420p", "-preset", "veryfast",
            "-c:a", "aac", "-b:a", "128k",
            "-shortest", out_path,
        ]
        subprocess.run(cmd, check=True, capture_output=True)
        with open(out_path, "rb") as fh:
            return fh.read()
    finally:
        shutil.rmtree(tmpdir, ignore_errors=True)


@app.post("/lipsync/generate")
async def lipsync_generate(
    audio:     UploadFile = File(...),
    avatar_id: str        = Form(...),
):
    """
    Receive raw audio (WAV preferred), pitch-shift per the avatar's voice
    profile, then run Wav2Lip to generate a video of the avatar lip-syncing
    that transformed audio. Returns MP4 bytes.
    """
    if avatar_id not in _AVATAR_MAP:
        raise HTTPException(status_code=404, detail=f"Unknown avatar_id: {avatar_id}")
    if _wav2lip is None:
        raise HTTPException(
            status_code=503,
            detail="Wav2Lip not loaded. Download wav2lip_gan.onnx into models/models/",
        )

    audio_bytes = await audio.read()
    if not audio_bytes:
        raise HTTPException(status_code=400, detail="Empty audio upload")

    loop = asyncio.get_event_loop()
    try:
        # First pitch-shift the audio per the avatar's _VOICE_FX
        wav_bytes = await loop.run_in_executor(
            None, _transform_voice, audio_bytes, avatar_id
        )
        # Then generate the lip-synced video
        mp4_bytes = await loop.run_in_executor(
            None, _lipsync_generate, wav_bytes, avatar_id
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Lip sync failed: {e}")

    return Response(content=mp4_bytes, media_type="video/mp4")


# ─────────────────────────────────────────────────────────────────────────────
#  WebSocket — live face swap
# ─────────────────────────────────────────────────────────────────────────────
@app.websocket("/ws/live-swap")
async def ws_live_swap(ws: WebSocket):
    await ws.accept()

    src_img       = None
    src_detection = None   # cached once — saves ~100ms/frame
    src_hair_mask = None   # BiSeNet hair mask of source (cached per session)
    processing    = False
    loop          = asyncio.get_event_loop()

    async def send(obj):
        await ws.send_text(json.dumps(obj))

    try:
        while True:
            raw = await ws.receive_text()
            msg = json.loads(raw)

            if msg["type"] == "init":
                if "avatar_id" in msg:
                    av_id      = msg["avatar_id"]
                    cache_path = _AVATAR_CACHE / f"{av_id}.jpg"
                    if av_id not in _AVATAR_MAP:
                        await send({"type":"error","message":"Unknown avatar"})
                        continue
                    if not cache_path.exists():
                        await send({"type":"error",
                                    "message":"Avatar not generated yet. Run generate_avatars.py."})
                        continue
                    src_img = await loop.run_in_executor(None, _decode_image, cache_path.read_bytes())
                else:
                    img_bytes = base64.b64decode(msg["source_image"])
                    src_img   = await loop.run_in_executor(None, _decode_image, img_bytes)

                # Cache source face detection once — never re-run per frame
                src_detection = await loop.run_in_executor(None, _detect, src_img)
                _, kps, bbox, is_real = src_detection
                if kps is None and not is_real:
                    await send({"type":"error","message":"No face detected in source image"})
                    src_img = src_detection = src_hair_mask = None
                else:
                    # Pre-compute source hair mask once if BiSeNet is loaded
                    if _face_parser is not None:
                        try:
                            src_hair_mask = await loop.run_in_executor(
                                None, _face_parser.hair_mask, src_img
                            )
                        except Exception:
                            src_hair_mask = None
                    await send({"type":"ready"})

            elif msg["type"] == "frame":
                if src_img is None:
                    await send({"type":"error","message":"Send init first"})
                    continue
                if processing:
                    await send({"type":"dropped"})
                    continue

                processing = True
                try:
                    frame_bytes = base64.b64decode(msg["image"])
                    frame  = await loop.run_in_executor(None, _decode_image, frame_bytes)
                    # Hair transfer disabled in the live loop — the warped
                    # avatar forehead was bleeding over the inswapper face
                    # region. Will re-enable with proper face-exclusion masks
                    # next session.
                    result = await loop.run_in_executor(
                        None, _swap_live, src_img, src_detection, frame
                    )
                    if result is None:
                        await send({"type":"no_face"})
                    else:
                        _, buf = cv2.imencode(".jpg", result, [cv2.IMWRITE_JPEG_QUALITY, 92])
                        await send({"type":"result","image": base64.b64encode(buf).decode()})
                finally:
                    processing = False

    except WebSocketDisconnect:
        pass
    except Exception as e:
        with contextlib.suppress(Exception):
            await send({"type":"error","message":str(e)})


# ─────────────────────────────────────────────────────────────────────────────
#  Streaming voice — low-latency pitch shift over WebSocket
# ─────────────────────────────────────────────────────────────────────────────
@app.websocket("/ws/voice-stream")
async def ws_voice_stream(ws: WebSocket):
    """
    Real-time voice transform.

    Client → server (text init):
        {"type":"init", "avatar_id":"gen_f_01"}
    Client → server (binary):
        Float32 PCM @ 16 kHz mono, ~500 ms chunks

    Server → client:
        Float32 PCM @ 16 kHz mono — same chunk pitch-shifted to the avatar
        voice profile. Client should schedule contiguous playback.
    """
    await ws.accept()
    avatar_id   = None
    semitones   = 0
    sr_in       = 16000   # client sends 16 kHz; if not, we resample
    loop        = asyncio.get_event_loop()

    async def _shift(pcm: np.ndarray) -> np.ndarray:
        if semitones == 0 or pcm.size == 0:
            return pcm
        # librosa pitch_shift preserves duration; just changes the pitch
        return librosa.effects.pitch_shift(pcm.astype(np.float32),
                                           sr=sr_in, n_steps=semitones)

    try:
        while True:
            msg = await ws.receive()
            if msg.get("type") == "websocket.disconnect":
                break
            text = msg.get("text")
            data = msg.get("bytes")

            if text is not None:
                try:
                    payload = json.loads(text)
                except Exception:
                    await ws.send_text(json.dumps({"type":"error","message":"bad json"}))
                    continue
                if payload.get("type") == "init":
                    avatar_id = payload.get("avatar_id")
                    if avatar_id and avatar_id in _AVATAR_MAP:
                        # Match longest voice-fx prefix
                        for prefix in sorted(_VOICE_FX.keys(), key=len, reverse=True):
                            if avatar_id.startswith(prefix):
                                semitones = _VOICE_FX[prefix]["semitones"]
                                break
                    await ws.send_text(json.dumps({
                        "type": "ready",
                        "semitones": semitones,
                        "sample_rate": sr_in,
                    }))
                continue

            if data is None:
                continue
            # Binary PCM Float32 mono @ 16 kHz
            pcm = np.frombuffer(data, dtype=np.float32)
            if pcm.size == 0:
                continue
            try:
                shifted = await loop.run_in_executor(None, lambda: _shift(pcm))
            except Exception as e:
                with contextlib.suppress(Exception):
                    await ws.send_text(json.dumps({"type":"error","message":str(e)}))
                continue
            await ws.send_bytes(shifted.astype(np.float32).tobytes())

    except WebSocketDisconnect:
        pass
    except Exception:
        # Don't crash the server on per-session errors
        pass


# ─────────────────────────────────────────────────────────────────────────────
#  Entrypoint
# ─────────────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    import uvicorn
    uvicorn.run(
        "main:app",
        host="0.0.0.0",
        port=7860,
        reload=False,
        workers=1,          # GPU models must stay in one process
    )
